BAH-1580|Samar|Script to create CSVs of patients and encounters
Bahmni/bahmni-scripts pull request #16
Opened 2022-04-28 06:33 UTC by samar-tw

- The maven based repo is based on Java 8, java-faker library. 
- It creates test data for patients registration and encounters of patients in CSV format. 
- These files can be imported into app via admin console and ready to be used.
- Note: These data are only for testing purpose.

2022-04-28 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Bahmni/bahmni-scripts?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Bahmni/bahmni-scripts?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Bahmni/bahmni-scripts?pullRequest=16) it.</sub>

2022-05-04 06:56 UTC, gsluthra commented on TestDataGenerator/src/main/java/PatientProfile.java
> +        "Birth Date", "Address.Village", "Address.Tehsil", "Address.District", "Address.State"};
Just note that this is dependant on Bahmni server configuration. for instance: "default-config" may specify these fields... in AddressHierarchy setup. But the "clinic-config" based Bahmni server setup might have different address hierarchy.. and in that case this script won't work. 

Please see if u can mention this information in your folder README.. to indicate the assumputions you made or the config folder this script runs with.

2022-05-04 06:57 UTC, gsluthra commented on TestDataGenerator/src/main/java/ContactProfile.java
> +                  "Repeat.1.Obs.Chief Complaint Duration","Repeat.1.Obs.Chief Complaint Notes",
Same comment here too (dependant on specific Bahmni server configuration.. likely default-config).

2022-05-04 08:34 UTC, N0-man requested changes
@samar-tw  few things
- Why put this into Bahmni Scripts? I believe this is agnostic utility and would be shared across test suits - in which case I would isolate it into its own repo.
- Why choose Java 8? 
- Why Maven? I would strongly consider Gradle
- Test coverage is missing

2022-05-05 04:40 UTC, closed without merging